# **House Price Model**

To start off, we will load the following Python modules below. They will be used in this notebook.

In [83]:
import pandas as pd




from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

## **Introduction**

The prediction of property prices is becoming increasingly important and beneficial. Property prices are a good indicator of both overall market condition and the economic health of a country. The dataset we are working on is house prices through the entire United States. Prices may vary depending on size, location of the house, the quality of the neighborhood, etc. These are called features and we will use these featrues to predict the f(x)=y.

## **Understanding our Data**

### Reading the Data File

We want to start off by reading our data file. I have my file in a seperate directory and I will use it's path to have pandas read the .xls file. We will use the read_excel() function in order to get an understanding of our data.

In [84]:
house_data = pd.read_csv('https://raw.githubusercontent.com/KylePineiroCode/house_price_ml/refs/heads/main/data/house_price_dataset.csv')
house_data.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

Looking at the top 5 house in our dataset using the .head() we come to find our features for our f(x)=y. Those features are: area, bedroom count, bathroom count, floors, year built, location, condition, and garage. Finally, our f(x)=y (the thing we are trying to predict) is the house price. Below I willl get some more information by using the .info() and .describe().

In [85]:
house_data.describe()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000
mean,1000.500000,2786.209500,3.003500,2.55250,1.993500,1961.446000,537676.855000
std,577.494589,1295.146799,1.424606,1.10899,0.809188,35.926695,276428.845719
min,1.000000,501.000000,1.000000,1.00000,1.000000,1900.000000,50005.000000
25%,500.750000,1653.000000,2.000000,2.00000,1.000000,1930.000000,300098.000000
50%,1000.500000,2833.000000,3.000000,3.00000,2.000000,1961.000000,539254.000000
75%,1500.250000,3887.500000,4.000000,4.00000,3.000000,1993.000000,780086.000000
max,2000.000000,4999.000000,5.000000,4.00000,3.000000,2023.000000,999656.000000

In [86]:
house_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   object
 7   Condition  2000 non-null   object
 8   Garage     2000 non-null   object
 9   Price      2000 non-null   int64
dtypes: int64(7), object(3)
memory usage: 156.4+ KB

## **Encoding our Categorical Data**

I notice that we have three columns that are categorical. Those features are location, condition, and garage. I'm going to read each column to see how I would like to turn them into numerical values using different encdoing techniques.

In [87]:
loc_col = house_data['Location']
loc_col.unique()

array(['Downtown', 'Suburban', 'Urban', 'Rural'], dtype=object)

In [88]:
cond_col = house_data['Condition']
cond_col.unique()

array(['Excellent', 'Good', 'Fair', 'Poor'], dtype=object)

In [89]:
garage_col = house_data['Garage']
garage_col.unique()

array(['No', 'Yes'], dtype=object)

Since the category 'Location' may have very small affect on the cost of price and living in one place is not better than the other I will use a OneHotEncoder us scikit-learn.

In [90]:

encoder = OneHotEncoder(sparse_output=False)
location_data = encoder.fit_transform(house_data[['Location']])
location_df = pd.DataFrame(location_data, columns=encoder.get_feature_names_out(['Location']))
house_data = pd.concat([house_data, location_df], axis=1)
house_data.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919,1.0,0.0,0.0,0.0
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998,1.0,0.0,0.0,0.0
2,3,3592,2,2,3,1938,Downtown,Good,No,266746,1.0,0.0,0.0,0.0
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020,0.0,0.0,1.0,0.0
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056,1.0,0.0,0.0,0.0

For the Condition of the house we see there are 4 different conditions. It is basically in order from 'Excellent' to 'Poor'. I am going to use ordinal encooding to make sure the value matches in a specific order. 0 = Excellet, 1 = Good, 2 = Fair, 3 = Poor.

In [91]:
categories_order = ['Excellent', 'Good', 'Fair', 'Poor']
encoder = OrdinalEncoder(categories=[categories_order])
house_data['Condition_Encoded'] = encoder.fit_transform(house_data[['Condition']])
house_data['Condition_Encoded'] = house_data['Condition_Encoded'].astype(int)
print(house_data[['Condition', 'Condition_Encoded']].head())
house_data.head()

   Condition  Condition_Encoded
0  Excellent                  0
1  Excellent                  0
2       Good                  1
3       Fair                  2
4       Fair                  2

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban,Condition_Encoded
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919,1.0,0.0,0.0,0.0,0
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998,1.0,0.0,0.0,0.0,0
2,3,3592,2,2,3,1938,Downtown,Good,No,266746,1.0,0.0,0.0,0.0,1
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020,0.0,0.0,1.0,0.0,2
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056,1.0,0.0,0.0,0.0,2

For the garage I will do a simple mapping because it is only 'Yes' or 'No'. A house having a garage will affect the price of a house.

In [92]:
house_data['Garage_Encoded'] = house_data['Garage'].map({'No': 0, 'Yes': 1})
house_data.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban,Condition_Encoded,Garage_Encoded
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919,1.0,0.0,0.0,0.0,0,0
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998,1.0,0.0,0.0,0.0,0,0
2,3,3592,2,2,3,1938,Downtown,Good,No,266746,1.0,0.0,0.0,0.0,1,0
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020,0.0,0.0,1.0,0.0,2,1
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056,1.0,0.0,0.0,0.0,2,1

In [93]:
house_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 2000 non-null   int64
 1   Area               2000 non-null   int64
 2   Bedrooms           2000 non-null   int64
 3   Bathrooms          2000 non-null   int64
 4   Floors             2000 non-null   int64
 5   YearBuilt          2000 non-null   int64
 6   Location           2000 non-null   object
 7   Condition          2000 non-null   object
 8   Garage             2000 non-null   object
 9   Price              2000 non-null   int64
 10  Location_Downtown  2000 non-null   float64
 11  Location_Rural     2000 non-null   float64
 12  Location_Suburban  2000 non-null   float64
 13  Location_Urban     2000 non-null   float64
 14  Condition_Encoded  2000 non-null   int64
 15  Garage_Encoded     2000 non-null   int64
dtypes: float64(4), int64(9), object(3)
memory usage: 250.1+ KB